### ISSUE TITLE
Warning when using imports from Data.LanguageCodes

### ISSUE THREAD

**Issue by jonpetterbergman** [HugoDaniel/iso639#1]
When using imports from Data.LanguageCodes there is a warning that the code is autogenerated and should not be changed. Not shure this warning is needed as it will yield warnings every time you compile something that uses Data.LanguageCodes.

**Comment by koterpillar** [comment]
This means no project can use this and `-Werror` at the same time.

**Comment by HugoDaniel** [comment]
Thank you, I uploaded a new version with the patch to hackage (0.1.0.3). The patch changed the generator to stop putting the warning in the beginning of the module.

**Comment by koterpillar** [comment]
The module on GitHub (https://github.com/HugoDaniel/iso639/blob/master/Data/LanguageCodes.hs) still has the warning. This will not be an issue when installing with Hackage, but it will confuse people trying to as much as rebuild the package themselves.
